### ISSUE TITLE
No configured connection to host 'localhost'

### ISSUE THREAD

**Issue by anarak** [eclipse/eavp#152]
When creating a plot using VisIt viz service, I got the following error:
```
Caused by: java.lang.Exception: ConnectionVizService error: No configured connection to host "localhost".
	at org.eclipse.eavp.viz.service.connections.ConnectionVizService.createPlot(ConnectionVizService.java:91)

```
This error is thrown because
a) `connectionByHost` in `VizConnectionManager` is called before it's initialized, or
b) `connectionByHost` never meant to contain/recognize 'localhost' as its member element, as implementation of `getConnectionsForHost` allows for `connectionByHost` to be null. But then, the next stack call throws this error saying it can't be null.

Did anyone try to consume EAVP's VisIt viz service before?

Solution to this would be having default connection values preset programmatically before calling `getConnectionsForHost`.

**Comment by jayjaybillings** [comment]
I'm looking at this now. Will you post you full stack trace please? Also, what branch are you using?

**Comment by anarak** [comment]
The branch is next, the stack trace is below:
```
!STACK 0
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:430)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bind(ServiceComponentProp.java:218)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:343)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: ConnectionVizService error: No configured connection to host "localhost".
	at org.eclipse.eavp.viz.service.connections.ConnectionVizService.createPlot(ConnectionVizService.java:91)
	at org.eclipse.eavp.viz.vaadin.WebEAVPUI.setVizServiceFactory(WebEAVPUI.java:121)
	... 16 more
Root exception:
java.lang.Exception: ConnectionVizService error: No configured connection to host "localhost".
	at org.eclipse.eavp.viz.service.connections.ConnectionVizService.createPlot(ConnectionVizService.java:91)
	at org.eclipse.eavp.viz.vaadin.WebEAVPUI.setVizServiceFactory(WebEAVPUI.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:430)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bind(ServiceComponentProp.java:218)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:343)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jayjaybillings** [comment]
Sorry, I don't have any additional insights to share. If I was you, I would run it through the debugger and see what the value of host is at ConnectionVizService.java:84.

@SmithRWORNL will probably have to fix this.

**Comment by anarak** [comment]
The value of host is null at ConnectionVizService.java:82 but then it's reassigned to 'localhost' at ConnectionVizService.java:84. I already debugged this issue and I explained its cause in the description.

**Comment by SmithRWORNL** [comment]
VisIt will no longer be supported in 0.3
